name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: ghcr.io/lindamthomas/python-docs-hello-world

    steps:
    - uses: actions/checkout@v3
    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_ID }}
        password: ${{ secrets.GHCR_PAT }}
        
    - name: Build the Docker image
      run: |
       docker build . --file Dockerfile --tag flask-api:latest
       docker tag flask-api $DOCKER_REPO:latest
       # Push to the repo
       docker push -a $DOCKER_REPO
       docker images
